### ISSUE TITLE
anterior spermathecal-uterine valve cells are isa and partof cells

### ISSUE THREAD

**Issue by cmungall** [raymond91125/Wao#4]
See image:

![asuj](https://cloud.githubusercontent.com/assets/50745/7581124/d89a1da8-f833-11e4-88ad-0645bc7649b0.png)

is this correct? Can something be a type of cell and a part of a cell at the same time?

In CL, syncytia are modeled as multi-nucleate cells; their parts are not themselves cells, AFAICT (ccing @dosumis for reality check on drosophila)

this is resulting in a minor incompatibility with uberon; for gory details see obophenotype/uberon#694

**Comment by raymond91125** [comment]
I removed the nonsensical relationship "spermathcal-uterine junction" is_a "smooth muscle". I believe this change should fix the 'co-exist is_a/part_of cell' problem.
https://github.com/raymond91125/Wao/commit/27eeee04b7bf494ee91140ded6982d28aee0474b
